{
 "title": "Home Automation",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "30s",
 "panels": [
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV",
   "type": "table",
   "gridPos": { "h": 3, "w": 10, "x": 5, "y": 0 },
   "targets": [
    {
     "measurement": "file",
     "query": "SELECT first(\"Uac1\") FROM \"file\" WHERE\n",
     "select": [
      [
       { "params": [ "Pac1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Leistung" ], "type": "alias" }
      ],
      [
       { "params": [ "EToday" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Tagesertrag" ], "type": "alias" }
      ],
      [
       { "params": [ "Uac1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Spannung" ], "type": "alias" }
      ],
      [
       { "params": [ "Iac1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Strom" ], "type": "alias" }
      ],
      [
       { "params": [ "Frequency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Frequenz" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vorhersage Herne",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Leistung AC Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "file",
     "select": [
      [
       { "params": [ "PacTot" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "String1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "file",
     "select": [
      [
       { "params": [ "Pdc1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "String2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "file",
     "select": [
      [
       { "params": [ "Pdc2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DC Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "file",
     "select": [
      [
       { "params": [ "PdcTot" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WAN",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Bits_IN" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Bits_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Wetter",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "celsius", "label": "Temp" }
   ],
   "targets": [
    {
     "alias": "Außentemperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UVR1611_metrics",
     "select": [
      [
       {
        "params": [
         "Data_Network Analog_4_Value_Value"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "-1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Außen relative Feuchte",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UVR1611_metrics",
     "select": [
      [
       {
        "params": [
         "Data_Network Analog_3_Value_Value"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Wind",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UVR1611_metrics",
     "select": [
      [
       { "params": [ "Data_Inputs_7_Value_Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "table",
   "gridPos": { "h": 3, "w": 15, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "Außen",
     "measurement": "UVR1611_metrics",
     "select": [
      [
       {
        "params": [
         "Data_Network Analog_4_Value_Value"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "-1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Wohnzimmer",
     "measurement": "UVR1611_metrics",
     "select": [
      [
       { "params": [ "Data_Inputs_2_Value_Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Bad",
     "measurement": "UVR1611_metrics",
     "select": [
      [
       { "params": [ "Data_Inputs_5_Value_Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Eltern",
     "measurement": "UVR1611_metrics",
     "select": [
      [
       { "params": [ "Data_Inputs_3_Value_Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Kind1",
     "measurement": "UVR1611_metrics",
     "select": [
      [
       { "params": [ "Data_Inputs_1_Value_Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Kind2",
     "measurement": "UVR1611_metrics",
     "select": [
      [
       { "params": [ "Data_Inputs_4_Value_Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Keller",
     "measurement": "UVR1611_metrics",
     "select": [
      [
       {
        "params": [
         "Data_Network Analog_7_Value_Value"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "-1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Steuerung UVR 1611",
   "type": "table",
   "gridPos": { "h": 3, "w": 15, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "Wärmepumpe",
     "measurement": "UVR1611_metrics",
     "select": [
      [
       { "params": [ "Data_Outputs_4_Value_Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Heizkreis",
     "measurement": "UVR1611_metrics",
     "select": [
      [
       { "params": [ "Data_Outputs_6_Value_Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "KWL EWT",
     "measurement": "UVR1611_metrics",
     "select": [
      [
       { "params": [ "Data_Outputs_5_Value_Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "KWL Keller",
     "measurement": "UVR1611_metrics",
     "select": [
      [
       { "params": [ "Data_Outputs_0_Value_State" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Gartenlicht",
     "measurement": "UVR1611_metrics",
     "select": [
      [
       { "params": [ "Data_Outputs_2_Value_Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Deckenlicht",
     "measurement": "UVR1611_metrics",
     "select": [
      [
       { "params": [ "Data_Outputs_3_Value_Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Raffstore",
     "measurement": "UVR1611_metrics",
     "select": [
      [
       { "params": [ "Data_Outputs_11_Value_Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}